/**
 * Static blog renderer. Generates public/blog/index.html from posts.ts.
 * Run: npx tsx src/blog/build.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { posts, type BlogPost } from './posts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SITE = 'https://starstore.app';
const OUT = join(__dirname, '..', '..', 'public', 'blog', 'index.html');

const escape = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const fmtDate = (iso: string) =>
  new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

const sorted = [...posts].sort((a, b) => (a.date < b.date ? 1 : -1));

const tocHtml = sorted
  .map(
    (p) => `
        <li>
          <a href="#${escape(p.slug)}" class="block py-2 px-3 rounded-lg hover:bg-indigo-50 hover:text-indigo-700 transition">
            <span class="font-medium">${escape(p.title)}</span>
            <span class="block text-xs text-gray-500 mt-0.5">${fmtDate(p.date)} · ${p.readMinutes} min read</span>
          </a>
        </li>`,
  )
  .join('');

const articlesHtml = sorted
  .map(
    (p: BlogPost) => `
      <article id="${escape(p.slug)}" class="insights-card rounded-xl p-6 sm:p-10 mb-10 scroll-mt-24" itemscope itemtype="https://schema.org/BlogPosting">
        <meta itemprop="datePublished" content="${escape(p.date)}" />
        <meta itemprop="author" content="StarStore" />
        <header class="mb-6">
          <h2 class="text-3xl sm:text-4xl font-bold text-gray-900 mb-3 tracking-tight" itemprop="headline">${escape(p.title)}</h2>
          <div class="flex flex-wrap items-center gap-x-3 gap-y-2 text-sm text-gray-500 mb-4">
            <time datetime="${escape(p.date)}" itemprop="datePublished">${fmtDate(p.date)}</time>
            <span aria-hidden="true">•</span>
            <span>${p.readMinutes} min read</span>
            <span aria-hidden="true">•</span>
            <span>By <span itemprop="author">StarStore Team</span></span>
          </div>
          <div class="flex flex-wrap gap-2">
            ${p.tags.map((t) => `<span class="badge text-xs px-2 py-1 rounded">${escape(t)}</span>`).join('')}
          </div>
          <p class="sr-only" itemprop="description">${escape(p.description)}</p>
        </header>
        <div class="prose prose-lg max-w-none" itemprop="articleBody">
          ${p.bodyHtml}
        </div>
        <footer class="mt-8 pt-6 border-t border-gray-200 flex flex-wrap items-center justify-between gap-3 text-sm">
          <a href="#top" class="text-indigo-600 hover:text-indigo-800">↑ Back to top</a>
          <a href="https://t.me/TgStarStore_bot" class="text-indigo-600 hover:text-indigo-800">Open StarStore in Telegram →</a>
        </footer>
      </article>`,
  )
  .join('');

const blogJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Blog',
  name: 'StarStore Insights',
  description: 'Guides, updates, and expert insights on Telegram Stars, Premium, and the StarStore platform.',
  url: `${SITE}/blog/`,
  publisher: { '@type': 'Organization', name: 'StarStore', url: SITE },
  blogPost: sorted.map((p) => ({
    '@type': 'BlogPosting',
    headline: p.title,
    description: p.description,
    datePublished: p.date,
    author: { '@type': 'Organization', name: 'StarStore' },
    url: `${SITE}/blog/#${p.slug}`,
    mainEntityOfPage: `${SITE}/blog/#${p.slug}`,
  })),
};

const breadcrumbsLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE}/` },
    { '@type': 'ListItem', position: 2, name: 'Blog', item: `${SITE}/blog/` },
  ],
};

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Generated by src/blog/build.ts. Do not edit by hand. -->
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>StarStore Insights — Guides, Updates & News on Telegram Stars</title>
  <meta name="description" content="In-depth guides, platform updates, and expert insights on Telegram Stars, Premium subscriptions, and the StarStore Mini App. All posts on one page." />
  <meta name="keywords" content="Telegram Stars, Telegram Premium, sell Telegram stars, buy Telegram stars, USDT, TON blockchain, StarStore blog" />
  <meta name="author" content="StarStore" />
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1" />
  <meta name="googlebot" content="index, follow" />

  <link rel="canonical" href="${SITE}/blog/" />

  <meta property="og:type" content="website" />
  <meta property="og:url" content="${SITE}/blog/" />
  <meta property="og:title" content="StarStore Insights — Telegram Stars Guides & Updates" />
  <meta property="og:description" content="Guides, updates, and expert insights on Telegram Stars and the StarStore platform — all in one place." />
  <meta property="og:image" content="${SITE}/favicon.png" />
  <meta property="og:site_name" content="StarStore" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:url" content="${SITE}/blog/" />
  <meta name="twitter:title" content="StarStore Insights — Telegram Stars Guides & Updates" />
  <meta name="twitter:description" content="Guides, updates, and expert insights on Telegram Stars and the StarStore platform." />
  <meta name="twitter:image" content="${SITE}/favicon.png" />

  <script async src="https://www.googletagmanager.com/gtag/js?id=G-SX6TDXG0N8"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-SX6TDXG0N8');
  </script>

  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="../css/blog.css" />
  <link rel="stylesheet" href="/css/theme.css" />
  <link rel="icon" type="image/png" href="../favicon.png" />
  <script src="/js/theme.js" defer></script>

  <script type="application/ld+json">${JSON.stringify(breadcrumbsLd)}</script>
  <script type="application/ld+json">${JSON.stringify(blogJsonLd)}</script>
</head>
<body class="bg-gray-50" id="top">
  <div class="min-h-screen">
    <header class="bg-white shadow-sm border-b sticky top-0 z-30">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center py-5">
          <div class="flex items-center">
            <a href="/" class="text-2xl font-bold text-indigo-600">StarStore</a>
            <span class="ml-3 text-gray-500 hidden sm:inline">Insights</span>
          </div>
          <nav class="flex items-center space-x-6 text-sm sm:text-base">
            <a href="/" class="text-gray-700 hover:text-indigo-600">Home</a>
            <a href="/about" class="text-gray-700 hover:text-indigo-600">About</a>
            <a href="/blog/" class="text-indigo-600 font-medium">Insights</a>
          </nav>
        </div>
      </div>
    </header>

    <main class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <section class="text-center mb-12 insights-hero">
        <h1 class="text-4xl md:text-5xl font-extrabold text-gray-900 mb-4 tracking-tight">StarStore Insights</h1>
        <p class="text-lg md:text-xl text-gray-600 max-w-3xl mx-auto">
          One page, every guide. Practical know-how for buying and selling Telegram Stars, growing referrals, and staying secure on the StarStore platform.
        </p>
        <div class="mt-6 flex flex-wrap items-center justify-center gap-3">
          <a href="/" class="inline-flex items-center px-5 py-2.5 rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 transition">Open the App</a>
          <a href="/referral" class="inline-flex items-center px-5 py-2.5 rounded-lg border border-gray-300 text-gray-700 hover:border-gray-400 transition">Referral Program</a>
        </div>
      </section>

      <nav aria-label="Table of contents" class="insights-card rounded-xl p-5 sm:p-6 mb-12">
        <h2 class="text-sm font-semibold uppercase tracking-wider text-gray-500 mb-3">In this issue</h2>
        <ul class="grid sm:grid-cols-2 gap-1">${tocHtml}
        </ul>
      </nav>

      <div>
${articlesHtml}
      </div>

      <section class="mt-12 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-xl p-8 text-center text-white">
        <h2 class="text-2xl font-bold mb-3">Stay in the loop</h2>
        <p class="text-indigo-100 mb-6 max-w-xl mx-auto">New guides, security updates, and product announcements — straight from the StarStore team.</p>
        <a href="https://t.me/TgStarStore_bot" class="inline-block bg-white text-indigo-700 px-6 py-2.5 rounded-lg font-medium hover:bg-gray-100 transition">Join us on Telegram</a>
      </section>
    </main>

    <footer class="bg-gray-900 text-white py-12 mt-16">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid md:grid-cols-4 gap-8">
          <div>
            <h3 class="text-xl font-bold mb-4">StarStore</h3>
            <p class="text-gray-400">Your trusted platform for Telegram Stars and Premium subscriptions.</p>
          </div>
          <div>
            <h4 class="font-semibold mb-4">Quick Links</h4>
            <ul class="space-y-2 text-gray-400">
              <li><a href="/" class="hover:text-white">Home</a></li>
              <li><a href="/about" class="hover:text-white">About</a></li>
              <li><a href="/blog/" class="hover:text-white">Insights</a></li>
            </ul>
          </div>
          <div>
            <h4 class="font-semibold mb-4">Services</h4>
            <ul class="space-y-2 text-gray-400">
              <li><a href="/" class="hover:text-white">Buy Stars</a></li>
              <li><a href="/sell" class="hover:text-white">Sell Stars</a></li>
              <li><a href="/referral" class="hover:text-white">Referral Program</a></li>
            </ul>
          </div>
          <div>
            <h4 class="font-semibold mb-4">Contact</h4>
            <ul class="space-y-2 text-gray-400">
              <li>Telegram: <a href="https://t.me/TgStarStore_bot" class="hover:text-white">@TgStarStore_bot</a></li>
              <li>Web: <a href="https://starstore.app" class="hover:text-white">starstore.app</a></li>
            </ul>
          </div>
        </div>
        <div class="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
          <p>&copy; ${new Date().getFullYear()} StarStore. All rights reserved.</p>
        </div>
      </div>
    </footer>
  </div>
</body>
</html>
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, html, 'utf8');
console.log(`✔ Generated ${OUT} (${sorted.length} posts)`);
             
